version: '3'
services:
  main:
    image: cubeearth/adjust-coreos-setup-iso
    privileged: true
#    cap_add:
#    - MKNOD
    volumes:
    - ${PROFILES_DIR}:/profiles:ro
    - ${OUTPUT_ISO_DIR}:/iso:rw
